### ISSUE TITLE
npm install error.npm ERR! Windows_NT 10.0.10240

### ISSUE THREAD

**Issue by bin-umar** [buckyroberts/angular-2-template#1]
npm WARN package.json angular-2@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0

npm ERR! shasum check failed for C:\Users\JAHONG~1\AppData\Local\Temp\npm-9028-942fea5e\registry.npmjs.org\angular2-\angular2-2.0.0-beta.13.tgz
npm ERR! Expected: e6b381345c958c57a4bd8bc7a29a1805983d040a
npm ERR! Actual:   583718ddd7344df5c4de7aa16dc2163cf843ae09
npm ERR! From:     https://registry.npmjs.org/angular2/-/angular2-2.0.0-beta.13.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\JAHONGIR-PC\WebstormProjects\Angular2\npm-debug.log

C:\Users\JAHONGIR-PC\WebstormProjects\Angular2>npm install
npm WARN package.json angular-2@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0

npm ERR! shasum check failed for C:\Users\JAHONG~1\AppData\Local\Temp\npm-1588-a9076f67\registry.npmjs.org\angular2-\angular2-2.0.0-beta.13.tgz
npm ERR! Expected: e6b381345c958c57a4bd8bc7a29a1805983d040a
npm ERR! Actual:   b325265e7c5dfa56eac132cba7dc2c49166753ce
npm ERR! From:     https://registry.npmjs.org/angular2/-/angular2-2.0.0-beta.13.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

**Comment by montel007** [comment]
what exactly are you trying to do?

**Comment by nathalav** [comment]
I have the same error trying to run npm install

**Comment by ericpark** [comment]
Hi! I don't have a windows machine so I can't test this out but I believe your versions are incompatible. Node and NPM are not the same thing. 

npm ERR! node v4.4.2
npm ERR! npm v2.15.0

This looks like you're using Node 4.4.2 but NPM 2.15.0. They should both be updated. You can reinstall node and then use the command npm update. :)
